### ISSUE TITLE
Issue when splitting on saved flow result

### ISSUE THREAD

**Issue by rudigiesler** [rapidpro/mailroom#174] opened 2019-09-10 09:48 UTC
When using the "Save flow result" option to save a value:

![image](https://user-images.githubusercontent.com/8234653/64603356-93e5c000-d3c0-11e9-9505-5956a8a9a39a.png)

Then when inspecting the flow results, the value seems to update correctly.

But when trying to split on a flow result:
![image](https://user-images.githubusercontent.com/8234653/64603455-bbd52380-d3c0-11e9-81d0-a1dab83012f0.png)

This does not work, the "Other" path will always be chosen, even when the saved value matches the criteria.

But when using the split by expression block:

![image](https://user-images.githubusercontent.com/8234653/64603536-df986980-d3c0-11e9-8b86-0c211f3443b9.png)

Then it does split correctly.

**Comment by rowanseymour** [comment] 2019-09-10 13:44
@rudigiesler can you share a sample flow for this?

**Comment by rudigiesler** [comment] 2019-09-11 09:45
@rowanseymour Here's a sample flow that exhibits this issue: https://gist.github.com/rudigiesler/ecabe65c8b82cec228715fbc895c3ea1

**Comment by rowanseymour** [comment] 2019-09-11 15:19
So that flow definitely looks broken - the operand for the split by result router is `@contact.webhook_failure_count`... instead of `@results.webhook_failure_count`. If I edit the node and save the flow it fixes itself.

But I can't replicate getting a flow into that state. Creating a new split sets the correct operand for me, and migrating a legacy flow also sets the correct operand. How did this flow get created?

**Comment by rudigiesler** [comment] 2019-09-11 15:26
I created this flow in the RapidPro UI, running the latest stable versions listed in the RapidPro repository: https://github.com/rapidpro/rapidpro#stable-versions

**Comment by ericnewcomer** [comment] 2019-09-11 17:03
That looks like a bug in your version of the editor. Keep in mind that the new editor is marked as beta for all current releases.

It does look correct in the current version, and I confirmed there was also a recent change to the operands used for these splits here: 
https://github.com/nyaruka/floweditor/pull/691/files

Update: I should also mention that I'm not aware of the new editor producing an operand like that and couldn't find evidence of it in the code. Perhaps it was migrated at some point or it's created in a way I don't understand. In any case, closing this. Please feel free to reopen if you can come up with a repro case so we can see exactly what produced it.

**Closed as completed by ericnewcomer** 2019-09-11 17:03 UTC

**Comment by rudigiesler** [comment] 2019-09-12 06:56
Thanks for the investigation, I can use the split by expression workaround until the next stable release, just want to make sure that it's a problem that's fixed in newer versions.
